import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar.jsx';
import { ToastContainer, toast } from "react-toastify"; 
import 'react-toastify/dist/ReactToastify.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

 


  return (
    <html lang="en">
      
      <body className={inter.className}>
      <Navbar  />
        {children}
        <ToastContainer position="top-right" autoClose={3000} hideProgressBar={false} /> 
        </body>
    </html>
  );
}
